name: check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Nix Flakes do not work on shallow clones
    - uses: cachix/install-nix-action@5a2cbac
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
        skip_adding_nixpkgs_channel: true
        extra_nix_config: experimental-features = nix-command flakes
    - run: nix flake check
